# Generated by Django 4.2.6 on 2023-10-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Eat', ' Eat'), ('Drink', ' Drink')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=200)),
            ],
        ),
    ]
