# Generated by Django 4.2.6 on 2023-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
