# Generated by Django 4.2.6 on 2023-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menumodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='img',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
